### ISSUE TITLE
第二版优化集中贴

### ISSUE THREAD

**Issue by terwer** [terwer/siyuan-plugin-blog#102]
- [ ] 1、移动端间距有点大，需要适配一下
- [x] 2、支持修改前缀为已经解析的域名
- [ ] 3、嵌入块支持 http://noob-service-publisher.siyuanplay.com/block/20230409064704-uk9z8n4
- [X] 4、图片问题修复 
 https://github.com/leolee9086/noob-service-publisher/tree/master/pipeRender/renders 参考这里的后端模块
https://github.com/leolee9086/noob-service-publisher/blob/master/pipeRender/renders/modifiers.js 图片的修复
- [ ] 5、客户端的逻辑包括文档树、图谱反链、大纲啥的在这里https://github.com/leolee9086/noob-service-publisher/blob/master/client/index.js
- [x] 支持设置自定义域名，域名解析需要自己做

**Comment by HowcanoeWang** [comment]
支持设置分享域名？就是简单的替换一下前面的IP:port为自定义域名，懒得复制时再修改了（

**Comment by terwer** [comment]
可以的。我下午改一下。域名解析需要你自己做哟。

**Comment by zmzdemo** [comment]
vercel怎么部署呀

**Comment by terwer** [comment]
设置环境变量即可，晚上我录个教程吧。

**Comment by terwer** [comment]
https://blog.terwer.space/s/20230621001422-xsimx5v 

完整的 vercel 部署教程看这里。

**Comment by terwer** [comment]
https://github.com/terwer/siyuan-plugin-blog/issues/208
单独建单跟踪，此单关闭
