### ISSUE TITLE
权限设置问题

### ISSUE THREAD

**Issue by APigggggg** [terwer/siyuan-plugin-blog#159]
根据我目前的使用经验，分享插件只能在网络伺服打开的状态下使用
而生成的分享链接有完整的ip地址和网络伺服端口号，也就是说在没有设置授权码的情况下，对方是可以访问完整工作空间的

是否可能生成一个新的端口，只用于在线分享，没有权限访问完整工作空间

**Comment by terwer** [comment]
目前插件版是SPA静态页面，无法做到。
你说的需求可使用vercel部署 或者 docker自部署，自部署支持自定义端口。

参考 https://blog.terwer.space/s/20230621001422-xsimx5v 这里面的docker相关教程。以及下面的视频教程

https://www.bilibili.com/video/BV1AV4y1a7Vi/
