### ISSUE TITLE
关闭分享后，链接仍能打开

### ISSUE THREAD

**Issue by pengcheng820** [terwer/siyuan-plugin-blog#200]
关闭分享后，链接仍能打开
版本：1.8.3

**Comment by terwer** [comment]
页面有缓存，需清空浏览器缓存


| |
youweics
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月4日 05:37 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-blog] 关闭分享后，链接仍能打开 (Issue #200) |

关闭分享后，链接仍能打开
版本：1.8.3

**Comment by pengcheng820** [comment]
是在浏览器隐私窗口模式下试的，依然可以

**Comment by terwer** [comment]
183我这里测试，问题没有复现。如有其他问题可再次反馈。

删除 data/public 尝试重新操作看看。可能是历史不兼容。

另外，就算隐私模式，浏览器本身还是有缓存的。需要ctrl+shift+delete删除缓存。或者自己等待浏览器缓存失效。

![image](https://github.com/terwer/siyuan-plugin-blog/assets/3259282/4b6e9106-bced-4fbd-82da-d7fb229ef090)

这是浏览器的基本机制。**本地文件有没有删除可直接去 data/public 查看，本地文件删除了就是取消成功。**
二浏览器的缓存你在访问其他问也也是这个机制。因为是静态html，所以缓存可能取决于浏览器策略。

**Comment by yikexiaoyao** [comment]
我关闭纯文字文档的分享后，将同一个链接放在另一个浏览器里还是能打开，该浏览器之前未打开过该链接

**Comment by yikexiaoyao** [comment]
建议时间戳后面使用随机码或者使用最新时间戳，每次打开默认重新生成，这样从整体上来看，地址发生了改变，应该可以解决问题，个人猜想，未经验证
