### ISSUE TITLE
多网卡情况，默认使用第一个网卡，无法访问

### ISSUE THREAD

**Issue by jokizhu** [terwer/siyuan-plugin-blog#217]
由于开启了多个网卡，默认使用了第一个，而分享想使用第二个网卡地址，如何解决？
![image](https://github.com/terwer/siyuan-plugin-blog/assets/128120301/33b8055c-5104-4ea1-a2c2-00048c0c8868)
![image](https://github.com/terwer/siyuan-plugin-blog/assets/128120301/f8d78854-e336-47f2-9091-7aa4c0ac5ba2)

**Comment by terwer** [comment]
插件图标上点击 右键 设置 设置自定义域名 

![image](https://github.com/terwer/siyuan-plugin-blog/assets/3259282/9ebf75a0-79f6-4e25-9378-d9f329ee5704)

**Comment by terwer** [comment]
设置了 自定义域名 会有优先使用，自定义域名写ip也可以，但是注意要是包括端口和http的完整地址。
