### ISSUE TITLE
【建议】创建分享链接时，把文章标题也带上

### ISSUE THREAD

**Issue by Ctipsy** [terwer/siyuan-plugin-blog#264]
【建议】创建分享链接时，把文章标题也带上
实际使用体验时，他人看到链接会有几个疑问：
① 这个链接样子很奇怪，不会是什么不正常链接吧
② 这个链接是啥？（尤其是消息很多的 办公场景，很容易遗忘）

修改样式举例：
我给你分享了一篇文章：xxxxxxx  （有效期 xxx小时）
打开链接：http://10.0.29.170:50201/plugins/siyuan-blog/#/s/xxxxxx 

具体信息样式建议配置成可选。

**Comment by terwer** [comment]
请升级 `1.10.0`
