### ISSUE TITLE
在线分享后显示401

### ISSUE THREAD

**Issue by wlinuxgit** [terwer/siyuan-plugin-blog#302]
![image](https://github.com/terwer/siyuan-plugin-blog/assets/48095549/4c7f3860-b271-4fd3-a7ab-d79e0213bda7)
公开分享，页面无法显示，部分请求显示401
思源版本：2.8.10
插件版本：1.8.5

**Comment by terwer** [comment]
![image](https://github.com/terwer/siyuan-plugin-blog/assets/3259282/82ca4a5a-f7fd-4e3e-aa31-de73af7803f9)

这个问题是新版本的思源增强了安全机制导致。所以我考虑同意分析行为。下版本修复。

**Comment by terwer** [comment]
`1.9.0` 已统一为静态分享，此问题应该不存在了。
