### ISSUE TITLE
【bug】笔记更新后，分享出去的链接打开后，不会同步更新

### ISSUE THREAD

**Issue by Ctipsy** [terwer/siyuan-plugin-blog#303]
如题，按Shift+F5强制刷新，仍不生效

**Comment by terwer** [comment]
不是bug。授权码模式分享每次都是缓存数据，有更新需要再次分享。这个原因是受限于技术现在，之前已经说过。

**Comment by ersanre** [comment]
怎么重新分享呢 我把分享按钮关掉后重新打开也不会生效

**Comment by terwer** [comment]
关掉重新打开就是重新分享。静态页面有缓存。可能需要刷新。

**Comment by Tsingwaa** [comment]
这个问题确实很明显，一般人点开并不会清除缓存。比如用网页端编辑，重新分享就不行

**Comment by terwer** [comment]
我试试看看能不能设置缓存过期策略。等待研究，目前还是只能手动清除缓存或者无痕模式。
