### ISSUE TITLE
关于在线分享，管理已经分享过的笔记

### ISSUE THREAD

**Issue by cnfniw** [terwer/siyuan-plugin-blog#348]
由于我的笔记比较多，可能有时分享了很多个。回头想关闭分享又忘记了那些是分享过的，像群晖里有个栏里面显示着已经分享过笔记本列表。再点取消就可以了。我看到这个插件上并没有类似的功能，还是说我不知道如何操作。

**Comment by terwer** [comment]
后续会加上这个功能。最近比较忙

**Comment by cnfniw** [comment]
好的，作者忙完了就帮忙更新一下，这个功能很实用。

**Comment by terwer** [comment]
https://github.com/terwer/siyuan-plugin-blog/issues/435
参考这里，专业版已支持。免费版暂时不支持。
