### ISSUE TITLE
docker版本点击“在线分享”没有反应

### ISSUE THREAD

**Issue by TRAVISZHAN** [terwer/siyuan-plugin-blog#349]
![ED586720C8B41BF3B25B84B1040CEAFE](https://github.com/terwer/siyuan-plugin-blog/assets/82930014/a090cfb9-a94d-4799-8d86-a4744691c22b)
我的docker版本设置栏在底部有一个块，不是在上面。而且点击“在线分享”没有任何反应。docker版本为最新，插件也是最新

**Comment by TRAVISZHAN** [comment]
> 我使用的是 v2.10.15 的docker 版本使用分享插件没有问题，就是不能管理已分享的。

可以了，浏览器更新了一下就能用了

**Comment by terwer** [comment]
看上面已经解决，如果有新问题可再次提出。
