### ISSUE TITLE
1.9.1版本.暗色模式丢失了，以及能否开发个默认暗黑模式呀？

### ISSUE THREAD

**Issue by xiao-linxin** [terwer/siyuan-plugin-blog#385]
![image](https://github.com/terwer/siyuan-plugin-blog/assets/20390177/4d1414e7-1d91-49d1-af03-f49a3325499d)
1.9.1版本.暗色模式丢失了

**Comment by terwer** [comment]
确实存在这个问题，之前支持了底部自定义，这块给弄没了。下版本计划加到页面上做个按钮。

**Comment by terwer** [comment]
暗色模式切换他回来啦

![image](https://github.com/user-attachments/assets/cb3b499f-d0da-41e8-87ba-ee114d390ca3)

![image](https://github.com/user-attachments/assets/1bc43e10-386b-4fb0-995a-37f582f90612)
