### ISSUE TITLE
在docker上部署

### ISSUE THREAD

**Issue by liuxingar** [terwer/siyuan-plugin-blog#423]
如何自己在docker上部署，之前说明文档已失效

**Comment by evan-oy** [comment]
其实最好是直接在docker上直接部署思源，然后再使用该插件就跟本地安装插件完全一样，本地思源跟docker版本的思源做云同步，本地分享后，在docker服务器上的访问完全一样

**Comment by terwer** [comment]
文档已恢复

https://blog.terwer.space/s/20230621001422-xsimx5v

**Comment by evan-oy** [comment]
![image](https://github.com/user-attachments/assets/b66dad99-0143-47d2-8bfe-b7b7ff9278f3)
按文档编排部署了插件，插件访问ok了， 去思源进行发布分享，怎么发布出去到3000地址这个容器呢？

**Comment by Mowen-M** [comment]
> ![image](https://github.com/user-attachments/assets/b66dad99-0143-47d2-8bfe-b7b7ff9278f3)
> 
> 按文档编排部署了插件，插件访问ok了， 去思源进行发布分享，怎么发布出去到3000地址这个容器呢？

你好，同样的情况，请问是怎么解决的

**Comment by Mowen-M** [comment]
![image](https://github.com/user-attachments/assets/df61417a-05c7-41b5-a394-bcc68be85697)
它不知道为什么，应该是路径错了？

**Comment by Mowen-M** [comment]
不用在意了，已经搞好了

**Comment by evan-oy** [comment]
请问怎么解决的？

**Comment by Chen017** [comment]
> 不用在意了，已经搞好了

请问怎么解决

**Comment by Mowen-M** [comment]
> > 不用在意了，已经搞好了
> 
> 
> 
> 请问怎么解决

保证你思源那个内部分享的端口号和你插件docker填一样的就行了，我也没搞懂为什么但是works！

**Comment by Mowen-M** [comment]
> 请问怎么解决的？

保证你思源那个内部分享的端口号和你插件docker填一样的就行了，我也没搞懂为什么但是works！

**Comment by Chen017** [comment]
> > 请问怎么解决的？
> 
> 保证你思源那个内部分享的端口号和你插件docker填一样的就行了，我也没搞懂为什么但是works！

请问是有三个填端口号的地方 一个是在线分享插件填ip的时候附带的端口号 一个是dockercompose里面的端口号 一个是envdocker的端口号 你是怎么填的 我都填62803都加载不出了... 都填3000起码还有页面

**Comment by terwer** [comment]
问题已解决，暂时关闭
