### ISSUE TITLE
分享多篇文章后，没地方看到底哪些文章被分享了，以及设置了主页，并不能在主页看到全部分享的文章

### ISSUE THREAD

**Issue by evanvip** [terwer/siyuan-plugin-blog#435]
分享多篇文章后，没地方看到底哪些文章被分享了，以及设置了主页，并不能在主页看到全部分享的文章
建议：
1、在思源端，能有一个入口查看所有已经分享的文章，最好是点一个按钮，就能把整个文档树按原有的目录过滤出已经分享了的文章。

2、既然设置了主页，如果直接访问主页，就把整个已经分享的文章列在主页的左侧成为分享文档目录，第一篇就为主页，之后可以点左侧菜单切换其他分享的文章， 这样就跟语雀的文档一样成为分享知识库， 这才真正的成为blog 的状态。

3、1.9.0+ 使用了静态分享，这个能否做成一个人工可选的开关，选择动态分享则直接更新，选择静态分享则人工刷新后更新。

**Comment by terwer** [comment]
在线分享专业版完全满足 1、2。

https://github.com/terwerinc/siyuan-plugin-share-pro

![image](https://github.com/user-attachments/assets/8780a664-101d-49c0-8048-7c2f7a9dcfd8)

![image](https://github.com/user-attachments/assets/9e962ebc-20eb-47b7-8790-2c3214ed3d45)
