### ISSUE TITLE
我明明已经配置了五个Vercel环境变量,但是却报错:500 Cannot read properties of null (reading 'theme')

### ISSUE THREAD

**Issue by fishyer** [terwer/siyuan-plugin-blog#492]
我的6806端口可以访问的,auth码也没问题

**Comment by cly2625** [comment]
+1

**Comment by cly2625** [comment]
![Uploading Snipaste_2024-11-14_09-52-00.png…]()

**Comment by cly2625** [comment]
![image](https://github.com/user-attachments/assets/dcbdbb44-43f5-48dc-9d34-042ff9194dd6)

**Comment by terwer** [comment]
未能复现问题。

https://freeshare.terwergreen.com/
