### ISSUE TITLE
帮助文档的域名是不是被墙了

### ISSUE THREAD

**Issue by B3000Kcn** [terwer/siyuan-plugin-blog#496]
我直接点是打不开的，添加到代理规则里就能打开了
![图片](https://github.com/user-attachments/assets/7104a180-0ad6-43fc-9f94-a172a7f065eb)
![图片](https://github.com/user-attachments/assets/1cb20df1-edb8-4274-b1c6-f9e54918497b)

**Comment by terwer** [comment]
没有，走全球 cdn。国内可访问 https://share.terwergreen.com/s/20230621001422-xsimx5v
