### ISSUE TITLE
docker版思源从集市安装后，点启用没反应

### ISSUE THREAD

**Issue by m1732948116** [terwer/siyuan-plugin-blog#540]
如图，点启用后没有图标也无法设置，重新安装或者升级思源也是一样
但是付费版就没有这个问题
![微信图片_20241203164707](https://github.com/user-attachments/assets/33e73fe4-e99e-4deb-bbaf-fe0d51d79e66)

**Comment by m1732948116** [comment]
几个月前第一次使用这个插件是可以的，版本忘记了，可能是升级插件导致的

**Comment by hausen1012** [comment]
我也有这个问题，升级以后导致的

**Comment by Mowen-M** [comment]
加一

**Comment by ZGeek** [comment]
插件升级到最新版本，然后进入到插件目录，修改index.js，在第556行。${datadir}/workspace/data/plugins/siyuan-blog/index.js

![image](https://github.com/user-attachments/assets/d951daa8-9370-439f-b2b0-317eafe21d1c)

**Comment by baicai12138** [comment]
有用！楼上说的可以用，修改下index.js就能显示出来了。

**Comment by terwer** [comment]
fixed in `5.3.0`
